#define DEFAULT_FREPAIR_VER "1P"

#define STR_FIELD_REPAIR "Feldreparatur"
#define STR_CANCEL_ACTION "Aktion abbrechen"
#define STR_SERIOUS_REPAIR "Komplettreparatur"
#define STR_ANOTHER_ACTION "Andere Aktion im Gange!"
#define STR_NEED_TOOLKIT "Du hast keine weiteren Ersatzteile parat, besorge einen Pionier, um zu reparieren!"
#define STR_REPAIR_INTERRUPTED "Reparatur unterbrochen"
#define STR_REPAIR_FINISHED "Reparatur beendet"
#define STR_REPAIR_MSG_STRING "Reparatur von %2 dauert %1 s..."
#define STR_REPAIR_TRUCK_DEPLETED "Keine weiteren Ersatzteile im Rep-LKW vorhanden."
#define STR_HELP "Realistic field repair script by Zealot: <br/> Das Script erlaubt es jedem Spieler, beschädigte Fahrzeuge einmalig mit Ersatzteilen zu reparieren. <br/>- Die Reparatur dauert je nach Schweregrad des Schadens zwischen 30 und 240 Sekunden. Die Reparatur kann abgebrochen und an der gleichen Stelle wieder aufgenommen werden. <br/>- Jedes Fahrzeug kann einmalig mit vorhandenen Ersatzteilen repariert werden. Danach benötigt man eine Werkzeugbox im Rucksack (nur Pio-Slots). <br/>- Reparaturen stellen das Fahrzeug nicht immer wieder komplett her (manche Teile bleiben gelb).<br/>- Reparaturen an Rep-LKW dauern 3 Minuten und stellen die Fahrzeuge komplett wieder her. Ein Rep-LKW kann 5 mal für Reparaturen genutzt werden, danach sind die Ersatzteile in ihm erschöpft.<br/>- Um den Rep-LKW zu nutzen, einfach auf den Fahrersitz setzen und mit Blick auf das beschädigte Fahrzeug und Komplettreparatur auswählen!<br/>"
#define STR_SCRIPTS_NAME "Scripts"
#define STR_SCRIPT_NAME "Field repair"
#define STR_PUSH_APC "Push vehicle"
#define FIELDREPAIR_MIN_DAMAGE_FOR_EASY_PARTS 0.2